import './calculator'
import './navbar'
import './slider'
import './cookies'
import './animationPictures'

import './animate.css'
import './calculator.css'
import './feature-1hero.css'
import './feature-3-zapis-premiera.css'
import './footer.css'
import './normalize.css'
import './product.css'
import './style-navbar.css'
import './styles2.css'
